using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace AzureBank.Api.Transformers;

/// <summary>
/// Adds <c>errorCode</c> and <c>traceId</c> to the shared <c>ProblemDetails</c> component, because
/// the API puts <c>traceId</c> on every error and <c>errorCode</c> on every error that names a
/// reason, and the published contract declared neither.
/// </summary>
/// <remarks>
/// <para>
/// MEASURED before writing this, one HTTP call per row against the running API rather than read off
/// the source. A 401, a 403 and a 404 all come back <c>application/json</c> carrying the same seven
/// keys — <c>type, title, status, detail, instance, errorCode, traceId</c> — for example:
/// </para>
/// <code>
/// {"type":"https://httpstatuses.com/403","title":"Forbidden","status":403,
///  "detail":"You do not have access to this account.","instance":"/api/accounts/01a015bb-…",
///  "errorCode":"ACCESS_DENIED","traceId":"ce10bb069afcbbb8fbf051eef6fe4bd0"}
/// </code>
/// <para>
/// The component is generated by reflecting <c>Microsoft.AspNetCore.Mvc.ProblemDetails</c>, whose
/// two extras live in an <c>Extensions</c> dictionary and therefore cannot appear in the reflected
/// schema. Patching the component here rather than changing 36 <c>[ProducesResponseType]</c> call
/// sites is deliberate: every one of them improves at once, and a new endpoint that points at the
/// shared component inherits the truth instead of having to remember it. Fifteen responses already
/// carry a HAND-WRITTEN inline schema declaring <c>errorCode</c> — that duplication is the symptom
/// of the shared route having been unusable, and it is what this makes unnecessary.
/// </para>
/// <para>
/// Both are OPTIONAL, and that is measured too rather than conservative. A validation 400 carries
/// <c>traceId</c> and an <c>errors</c> dictionary but NO <c>errorCode</c>:
/// <c>{"type":"…rfc9110#section-15.5.1","title":"One or more validation errors occurred.",
/// "status":400,"errors":{…},"traceId":"00-…"}</c>. Marking either required would publish a
/// contract wider than the code, which is the defect this whole change exists to remove — pointed
/// the other way.
/// </para>
/// </remarks>
public sealed class ProblemDetailsExtensionsTransformer : IOpenApiDocumentTransformer
{
    private const string ComponentName = "ProblemDetails";

    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken)
    {
        if (document.Components?.Schemas is null
            || !document.Components.Schemas.TryGetValue(ComponentName, out var existing)
            || existing is not OpenApiSchema schema)
        {
            /*
              Loud, not quiet. The component is present whenever any endpoint declares a
              ProblemDetails response, which every error path does; its absence means the generation
              pipeline changed shape and this transformer is silently doing nothing — the exact
              failure mode the guards work of #119 was about.
            */
            throw new InvalidOperationException(
                $"The '{ComponentName}' schema component was not found, so the error contract cannot "
                + "be completed. Either no endpoint declares a ProblemDetails response any more, or "
                + "the component was renamed; both would publish an error shape the API does not send.");
        }

        schema.Properties ??= new Dictionary<string, IOpenApiSchema>();

        schema.Properties["errorCode"] = new OpenApiSchema
        {
            Type = JsonSchemaType.String,
            Description =
                "Stable, machine-readable identifier for the failure — the value clients branch on. "
                + "Absent only on validation failures, which carry an 'errors' dictionary instead.",
        };

        schema.Properties["traceId"] = new OpenApiSchema
        {
            Type = JsonSchemaType.String,
            Description =
                "Correlates this response with the server-side log entry. Quote it in a bug report.",
        };

        return Task.CompletedTask;
    }
}
