import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

const HEX_MESSAGE =
  'Hardcoded colour. Use a Fluent token (tokens.colorNeutralBackground1, tokens.colorNeutralForegroundOnBrand, …) for anything the theme should drive, or the local palette in src/theme/tokens.ts for what Fluent has no name for. See docs/brand-assets.md and frontend/CONVENTIONS.md.'

export default defineConfig([
  // schema.d.ts is generated by openapi-typescript (see generate:api) — not ours to lint.
  globalIgnores(['dist', 'src/api/schema.d.ts', 'public/mockServiceWorker.js']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Colour belongs in src/theme/ and nowhere else.
      //
      // This ships as an ERROR rather than a warning because the count is already zero: 90 literals
      // across 20 files were migrated to Fluent tokens and the local palette during U1, so there is
      // nothing to grandfather. A warning nobody violates is noise; an error nobody violates is a
      // closed door, and it is what makes dark mode possible at U7 — every hardcoded hex is a
      // surface that cannot follow a theme.
      //
      // Matched on string content rather than on the CSS property, because a colour reaches a style
      // through a variable, a template literal or a prop just as often as through `color:`.
      //
      // Two shapes × two node types, so four selectors. A 6- or 8-digit hex is unambiguous enough to
      // catch ANYWHERE inside a string (`1px solid #ff0000` is the common one); a 3- or 4-digit one
      // is matched only as a whole string, because un-anchored it would hit URL fragments and ids.
      // Both then have to be repeated for `TemplateElement`, which a `Literal` selector never visits
      // — and the pairs must stay symmetric. They were not at first: the template side carried only
      // the long form, so a bare `` `#fff` `` walked straight through the rule that exists to stop
      // exactly that. Add a shape to one side, add it to the other.
      //
      // The functional notations are caught too, as of the theme-tokens pass. This comment used to
      // end by admitting the opposite — "what it still does NOT catch: `rgba()` and `hsl()` calls
      // … there are 11 `rgba()` literals left in src/ for that reason" — and that sentence had gone
      // stale twice over: the count was down to three, and a hole a rule DOCUMENTS is still a hole.
      // Those three are now tokens, so the same argument that made the hex rule an error applies
      // here: the count is zero, so there is nothing to grandfather, and an error at zero is a
      // closed door rather than noise.
      //
      // What it still does not catch, stated plainly so nobody trusts it further than it goes:
      // named CSS colours (`white`, `tomato`), `color-mix()`, and a SHORT hex embedded in a longer
      // string. Anything that survives this rule is caught by reading, not by tooling.
      'no-restricted-syntax': [
        'error',
        {
          selector: "Literal[value=/#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6})(?![0-9a-fA-F])/]",
          message: HEX_MESSAGE,
        },
        {
          selector: "Literal[value=/^#[0-9a-fA-F]{3,4}$/]",
          message: HEX_MESSAGE,
        },
        {
          selector: "TemplateElement[value.raw=/#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6})(?![0-9a-fA-F])/]",
          message: HEX_MESSAGE,
        },
        {
          selector: "TemplateElement[value.raw=/^#[0-9a-fA-F]{3,4}$/]",
          message: HEX_MESSAGE,
        },
        // Both node types again, and they must stay symmetric — the hex pair above shipped
        // asymmetric once, and a bare `` `#fff` `` walked through the rule that existed to stop it.
        //
        // The `i` flag is load-bearing rather than tidy: CSS function names are case-insensitive, so
        // `RGBA(0, 0, 0, 0.5)` is exactly as valid as the lowercase form. Without the flag it walked
        // through — verified, not assumed, by putting one back and getting zero errors.
        {
          selector: 'Literal[value=/(?:rgba?|hsla?)\\(/i]',
          message: HEX_MESSAGE,
        },
        {
          selector: 'TemplateElement[value.raw=/(?:rgba?|hsla?)\\(/i]',
          message: HEX_MESSAGE,
        },
      ],
    },
  },
  {
    // src/theme/ is where colour is allowed to be spelled out — it is the definition, not a use.
    files: ['src/theme/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': 'off',
    },
  },
])
