/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all accounts for the authenticated user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of user's accounts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfListOfAccountResponse"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new bank account. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account creation details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountRequest"];
                    "text/json": components["schemas"]["CreateAccountRequest"];
                    "application/*+json": components["schemas"]["CreateAccountRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfAccountResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific account by ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfAccountResponse"];
                    };
                };
                /** @description Bad Request - Invalid parameter format or validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete (soft delete) an account.
         *     Balance must be zero and account cannot be primary.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Business Rule Violation - The request violates domain constraints (e.g., same account transfer, insufficient funds). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary (e.g., 'Business Rule Violation') */
                            title?: string;
                            /** @description The HTTP status code (422) */
                            status?: number;
                            /** @description A human-readable explanation of the business rule violation */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update account details (name only). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Update details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountRequest"];
                    "text/json": components["schemas"]["UpdateAccountRequest"];
                    "application/*+json": components["schemas"]["UpdateAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfAccountResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account balance (current or historical). */
        get: {
            parameters: {
                query?: {
                    /** @description Optional: Get balance at specific point in time (ISO 8601) */
                    at?: string;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfBalanceResponse"];
                    };
                };
                /** @description Bad Request - Validation failed. Check the errors property for details. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (400) */
                            status?: number;
                            /** @description Validation errors keyed by property name */
                            errors?: {
                                [key: string]: string[];
                            };
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/full-number": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reveal the full (unmasked) account number of one owned account.
         *     Every other endpoint returns the masked form; behind the BFF this exact path is
         *     step-up-gated (PIN, auth level 2) and the response must never be cached.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfAccountNumberResponse"];
                    };
                };
                /** @description Bad Request - Invalid parameter format or validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/set-primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set an account as the primary account. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID to set as primary */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request - Invalid parameter format or validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user and receive JWT token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfLoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account with initial bank account. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Registration details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user information. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfUserResponse"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set or update user's PIN for step-up authentication. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description PIN to set */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPinRequest"];
                    "text/json": components["schemas"]["SetPinRequest"];
                    "application/*+json": components["schemas"]["SetPinRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify user's PIN for step-up authentication. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description PIN to verify */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyPinRequest"];
                    "text/json": components["schemas"]["VerifyPinRequest"];
                    "application/*+json": components["schemas"]["VerifyPinRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction history with filtering and pagination. */
        get: {
            parameters: {
                query?: {
                    AccountId?: string;
                    FromDate?: string;
                    ToDate?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedResponseOfTransactionResponse"];
                    };
                };
                /** @description Bad Request - Validation failed. Check the errors property for details. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (400) */
                            status?: number;
                            /** @description Validation errors keyed by property name */
                            errors?: {
                                [key: string]: string[];
                            };
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific transaction by ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Transaction ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfTransactionResponse"];
                    };
                };
                /** @description Bad Request - Invalid parameter format or validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - The requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit money into an account. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated UUID that makes this monetary operation idempotent: retries with the same key and payload replay the original response (header Idempotency-Replayed: true) instead of executing twice. Missing => 400 IDEMPOTENCY_KEY_MISSING; malformed => 400 IDEMPOTENCY_KEY_INVALID. */
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Deposit details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepositRequest"];
                    "text/json": components["schemas"]["DepositRequest"];
                    "application/*+json": components["schemas"]["DepositRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Set to 'true' when this response is a byte-identical replay of a previously executed idempotent request (absent on first execution). */
                        "Idempotency-Replayed"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfDepositResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict - a request with this idempotency key is currently in flight (IDEMPOTENCY_IN_FLIGHT), or it executed but its response was not recorded (IDEMPOTENCY_RESULT_UNKNOWN: verify via GET /api/transactions). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (409) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Payload Too Large - the request body exceeds the 32 KB limit for these idempotent monetary endpoints (IDEMPOTENCY_PAYLOAD_TOO_LARGE); rejected before any hashing or claim. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (413) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Unprocessable Entity - business rule violation (e.g. INSUFFICIENT_FUNDS), or this idempotency key was already used with a different payload (IDEMPOTENCY_KEY_REUSE). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (422) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw money from an account.
         *     Requires PIN verification.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated UUID that makes this monetary operation idempotent: retries with the same key and payload replay the original response (header Idempotency-Replayed: true) instead of executing twice. Missing => 400 IDEMPOTENCY_KEY_MISSING; malformed => 400 IDEMPOTENCY_KEY_INVALID. */
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Withdrawal details including PIN */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WithdrawRequest"];
                    "text/json": components["schemas"]["WithdrawRequest"];
                    "application/*+json": components["schemas"]["WithdrawRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Set to 'true' when this response is a byte-identical replay of a previously executed idempotent request (absent on first execution). */
                        "Idempotency-Replayed"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfWithdrawResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict - a request with this idempotency key is currently in flight (IDEMPOTENCY_IN_FLIGHT), or it executed but its response was not recorded (IDEMPOTENCY_RESULT_UNKNOWN: verify via GET /api/transactions). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (409) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Payload Too Large - the request body exceeds the 32 KB limit for these idempotent monetary endpoints (IDEMPOTENCY_PAYLOAD_TOO_LARGE); rejected before any hashing or claim. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (413) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Unprocessable Entity - business rule violation (e.g. INSUFFICIENT_FUNDS), or this idempotency key was already used with a different payload (IDEMPOTENCY_KEY_REUSE). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (422) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer money to another user's primary account. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated UUID that makes this monetary operation idempotent: retries with the same key and payload replay the original response (header Idempotency-Replayed: true) instead of executing twice. Missing => 400 IDEMPOTENCY_KEY_MISSING; malformed => 400 IDEMPOTENCY_KEY_INVALID. */
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Transfer details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransferRequest"];
                    "text/json": components["schemas"]["TransferRequest"];
                    "application/*+json": components["schemas"]["TransferRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Set to 'true' when this response is a byte-identical replay of a previously executed idempotent request (absent on first execution). */
                        "Idempotency-Replayed"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfTransferResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict - a request with this idempotency key is currently in flight (IDEMPOTENCY_IN_FLIGHT), or it executed but its response was not recorded (IDEMPOTENCY_RESULT_UNKNOWN: verify via GET /api/transactions). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (409) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Payload Too Large - the request body exceeds the 32 KB limit for these idempotent monetary endpoints (IDEMPOTENCY_PAYLOAD_TOO_LARGE); rejected before any hashing or claim. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (413) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Unprocessable Entity - business rule violation (e.g. INSUFFICIENT_FUNDS), or this idempotency key was already used with a different payload (IDEMPOTENCY_KEY_REUSE). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (422) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/internal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer money between own accounts. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated UUID that makes this monetary operation idempotent: retries with the same key and payload replay the original response (header Idempotency-Replayed: true) instead of executing twice. Missing => 400 IDEMPOTENCY_KEY_MISSING; malformed => 400 IDEMPOTENCY_KEY_INVALID. */
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Internal transfer details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InternalTransferRequest"];
                    "text/json": components["schemas"]["InternalTransferRequest"];
                    "application/*+json": components["schemas"]["InternalTransferRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Set to 'true' when this response is a byte-identical replay of a previously executed idempotent request (absent on first execution). */
                        "Idempotency-Replayed"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfInternalTransferResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict - a request with this idempotency key is currently in flight (IDEMPOTENCY_IN_FLIGHT), or it executed but its response was not recorded (IDEMPOTENCY_RESULT_UNKNOWN: verify via GET /api/transactions). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (409) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Payload Too Large - the request body exceeds the 32 KB limit for these idempotent monetary endpoints (IDEMPOTENCY_PAYLOAD_TOO_LARGE); rejected before any hashing or claim. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (413) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Unprocessable Entity - business rule violation (e.g. INSUFFICIENT_FUNDS), or this idempotency key was already used with a different payload (IDEMPOTENCY_KEY_REUSE). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (422) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (e.g., 'INSUFFICIENT_FUNDS', 'IDEMPOTENCY_KEY_REUSE') */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{azureTag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a single user by their EXACT AzureTag, to confirm a transfer recipient.
         *     Returns the masked display name (e.g. "Vladislav A.") for confirmation. This is an
         *     exact-match confirmation oracle by design — there is deliberately no substring/prefix
         *     directory search, which would let an authenticated user harvest the customer list
         *     (ADR-0014; the Zelle/Cash App model).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Full AzureTag to look up (3-20 chars, AzureTag charset). */
                    azureTag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfRecipientLookupResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/azuretag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Renames the caller's own public AzureTag handle (ADR-0015). The handle is decoupled
         *     from the login identity (UserName is the immutable user id), so this is a plain update.
         *     The bearer token still carries the old handle in its azure_tag claim until it is
         *     refreshed on next login.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAzureTagRequest"];
                    "text/json": components["schemas"]["UpdateAzureTagRequest"];
                    "application/*+json": components["schemas"]["UpdateAzureTagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfUpdateAzureTagResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized - Authentication required. Provide a valid JWT Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - You don't have permission to access this resource. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict - the requested AzureTag is already taken (errorCode AZURE_TAG_TAKEN). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description A URI reference identifying the problem type */
                            type?: string;
                            /** @description A short, human-readable summary */
                            title?: string;
                            /** @description The HTTP status code (409) */
                            status?: number;
                            /** @description A human-readable explanation of the failure */
                            detail?: string;
                            /** @description Machine-readable error code (AZURE_TAG_TAKEN) */
                            errorCode?: string;
                            /** @description Request trace identifier for debugging */
                            traceId?: string;
                        };
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The on-demand reveal of a single account's FULL (unmasked) account number.
         *     Every other account DTO carries the masked form (AccountMapper); this dedicated type
         *     exists so the unmasked value is a deliberate, self-describing, separately-audited
         *     shape — never a field a generic mapping could adopt by accident.
         */
        AccountNumberResponse: {
            /** Format: uuid */
            accountId?: string;
            /** @description The full, unmasked account number (e.g. AB-1234-5678-90). */
            accountNumber: string;
        };
        AccountResponse: {
            /** Format: uuid */
            id?: string;
            accountNumber: string;
            name: string;
            type?: components["schemas"]["AccountType"];
            /** Format: double */
            balance?: number;
            isPrimary?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        /**
         * @description Type of bank account: Checking, Savings, Investment
         * @enum {string}
         */
        AccountType: "Checking" | "Savings" | "Investment";
        ApiResponse: {
            message?: null | string;
        };
        ApiResponseOfAccountNumberResponse: {
            data?: null | components["schemas"]["AccountNumberResponse"];
            message?: null | string;
        };
        ApiResponseOfAccountResponse: {
            data?: null | components["schemas"]["AccountResponse"];
            message?: null | string;
        };
        ApiResponseOfBalanceResponse: {
            data?: null | components["schemas"]["BalanceResponse"];
            message?: null | string;
        };
        ApiResponseOfDepositResponse: {
            data?: null | components["schemas"]["DepositResponse"];
            message?: null | string;
        };
        ApiResponseOfInternalTransferResponse: {
            data?: null | components["schemas"]["InternalTransferResponse"];
            message?: null | string;
        };
        ApiResponseOfListOfAccountResponse: {
            data?: null | components["schemas"]["AccountResponse"][];
            message?: null | string;
        };
        ApiResponseOfLoginResponse: {
            data?: null | components["schemas"]["LoginResponse"];
            message?: null | string;
        };
        ApiResponseOfObject: {
            data?: unknown;
            message?: null | string;
        };
        ApiResponseOfRecipientLookupResponse: {
            data?: null | components["schemas"]["RecipientLookupResponse"];
            message?: null | string;
        };
        ApiResponseOfRegisterResponse: {
            data?: null | components["schemas"]["RegisterResponse"];
            message?: null | string;
        };
        ApiResponseOfTransactionResponse: {
            data?: null | components["schemas"]["TransactionResponse"];
            message?: null | string;
        };
        ApiResponseOfTransferResponse: {
            data?: null | components["schemas"]["TransferResponse"];
            message?: null | string;
        };
        ApiResponseOfUpdateAzureTagResponse: {
            data?: null | components["schemas"]["UpdateAzureTagResponse"];
            message?: null | string;
        };
        ApiResponseOfUserResponse: {
            data?: null | components["schemas"]["UserResponse"];
            message?: null | string;
        };
        ApiResponseOfWithdrawResponse: {
            data?: null | components["schemas"]["WithdrawResponse"];
            message?: null | string;
        };
        /**
         * @description Response for balance inquiries (current or historical).
         *     Used by GET /api/accounts/{id}/balance endpoint.
         */
        BalanceResponse: {
            /**
             * Format: uuid
             * @description Account identifier
             */
            accountId?: string;
            /**
             * Format: double
             * @description Balance amount
             */
            balance?: number;
            /** @description Currency code (default: EUR) */
            currency?: string;
            /**
             * Format: date-time
             * @description Timestamp of the balance (current time or requested historical time)
             */
            asOf?: string;
            /** @description True if this is a historical balance query, false for current balance */
            isHistorical?: boolean;
        };
        CreateAccountRequest: {
            name: string;
            type: components["schemas"]["AccountType"];
        };
        DepositRequest: {
            /**
             * Format: uuid
             * @description A valid non-empty UUID is required.
             */
            accountId: string;
            /**
             * Format: double
             * @description Amount must be between $0.01 and $100,000.00.
             */
            amount: number;
            description?: null | string;
        };
        /**
         * @description Response returned after a successful deposit.
         *     Includes the created transaction and updated balance.
         */
        DepositResponse: {
            /** @description The created deposit transaction */
            transaction: components["schemas"]["TransactionResponse"];
            /**
             * Format: double
             * @description Updated account balance after the deposit
             */
            newBalance?: number;
        };
        InternalTransferRequest: {
            /**
             * Format: uuid
             * @description A valid non-empty UUID is required.
             */
            fromAccountId: string;
            /**
             * Format: uuid
             * @description A valid non-empty UUID is required.
             */
            toAccountId: string;
            /**
             * Format: double
             * @description Amount must be between $0.01 and $100,000.00.
             */
            amount: number;
            description?: null | string;
        };
        /**
         * @description Response returned after a successful internal transfer (between own accounts).
         *     Includes transfer details and both account balances.
         */
        InternalTransferResponse: {
            /**
             * Format: uuid
             * @description Unique transfer identifier
             */
            transferId?: string;
            /** @description Transaction number for reference */
            transactionNumber: string;
            /**
             * Format: uuid
             * @description Source account ID
             */
            fromAccountId?: string;
            /**
             * Format: uuid
             * @description Destination account ID
             */
            toAccountId?: string;
            /**
             * Format: double
             * @description Transfer amount
             */
            amount?: number;
            /** @description Optional transfer description */
            description?: null | string;
            /**
             * Format: double
             * @description Updated balance of the source account
             */
            fromAccountNewBalance?: number;
            /**
             * Format: double
             * @description Updated balance of the destination account
             */
            toAccountNewBalance?: number;
            /**
             * Format: date-time
             * @description Transfer completion timestamp
             */
            processedAt?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** @description Password must contain at least one uppercase, one lowercase, and one digit. */
            password: string;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["UserLoginInfo"];
        };
        PaginatedResponseOfTransactionResponse: {
            data?: components["schemas"]["TransactionResponse"][];
            pagination?: components["schemas"]["PaginationMetadata"];
        };
        PaginationMetadata: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: number;
            detail?: null | string;
            instance?: null | string;
        };
        /**
         * @description Response for recipient lookup by AzureTag.
         *     Used for transfer recipient verification.
         */
        RecipientLookupResponse: {
            /** @description The user's AzureTag */
            azureTag: string;
            /** @description Masked display name for privacy (e.g., "John D.") */
            displayName: string;
            /** @description Whether the user exists in the system */
            exists?: boolean;
        };
        RegisterRequest: {
            /** @description Must start with a letter and contain only lowercase letters, numbers, and underscores. */
            azureTag: string;
            /** Format: email */
            email: string;
            /** @description Password must contain at least one uppercase, one lowercase, and one digit. */
            password: string;
            firstName: string;
            lastName: string;
        };
        /**
         * @description Response returned after successful user registration.
         *     Includes user info, initial account, and authentication token.
         */
        RegisterResponse: {
            /** @description Registered user information */
            user: components["schemas"]["UserLoginInfo"];
            /** @description Initial primary account created for the user */
            account: components["schemas"]["AccountResponse"];
            /** @description Authentication token for immediate login */
            token: components["schemas"]["TokenResponse"];
        };
        SetPinRequest: {
            /** @description PIN must be exactly 6 digits. */
            pin: string;
        };
        /** @description Token information returned in authentication responses. */
        TokenResponse: {
            /** @description JWT access token */
            accessToken: string;
            /**
             * Format: int32
             * @description Token expiration time in seconds
             */
            expiresIn?: number;
            /** @description Token type (always "Bearer") */
            tokenType?: string;
            /**
             * Format: date-time
             * @description Absolute expiration timestamp
             */
            expiresAt?: string;
        };
        TransactionResponse: {
            /** Format: uuid */
            id?: string;
            transactionNumber: string;
            type?: components["schemas"]["TransactionType"];
            /** Format: double */
            amount?: number;
            /** Format: double */
            balanceAfter?: number;
            description?: null | string;
            recipientAzureTag?: null | string;
            senderAzureTag?: null | string;
            status?: components["schemas"]["TransactionStatus"];
            /** Format: date-time */
            createdAt?: string;
        };
        /**
         * @description Transaction Statuses: Pending, Completed, Failed, Reversed
         * @enum {string}
         */
        TransactionStatus: "Pending" | "Completed" | "Failed" | "Reversed";
        /**
         * @description Types of transaction: Deposit, Withdrawal, TransferIn, TransferOut
         * @enum {string}
         */
        TransactionType: "Deposit" | "Withdrawal" | "TransferIn" | "TransferOut";
        TransferRequest: {
            /**
             * Format: uuid
             * @description A valid non-empty UUID is required.
             */
            fromAccountId: string;
            /** @description Must start with a letter and contain only lowercase letters, numbers, and underscores. */
            recipientAzureTag: string;
            /**
             * Format: double
             * @description Amount must be between $0.01 and $100,000.00.
             */
            amount: number;
            description?: null | string;
        };
        TransferResponse: {
            transactionNumber: string;
            /** Format: double */
            amount?: number;
            /** Format: double */
            newBalance?: number;
            recipientAzureTag: string;
            recipientName?: null | string;
            /** Format: date-time */
            processedAt?: string;
        };
        UpdateAccountRequest: {
            name: string;
        };
        /** @description Request to rename the caller's own public AzureTag handle (ADR-0015). */
        UpdateAzureTagRequest: {
            azureTag: string;
        };
        /** @description The caller's AzureTag after a successful rename (ADR-0015). */
        UpdateAzureTagResponse: {
            azureTag: string;
        };
        /** @description User info returned after successful login (nested in LoginResponse) */
        UserLoginInfo: {
            /** Format: uuid */
            id: string;
            azureTag: string;
            email: string;
            firstName: string;
            lastName: string;
            hasPin?: boolean;
        };
        UserResponse: {
            /** Format: uuid */
            userId: string;
            azureTag: string;
            email: string;
            firstName: string;
            lastName: string;
        };
        VerifyPinRequest: {
            /** @description PIN must be exactly 6 digits. */
            pin: string;
        };
        WithdrawRequest: {
            /**
             * Format: uuid
             * @description A valid non-empty UUID is required.
             */
            accountId: string;
            /**
             * Format: double
             * @description Amount must be between $0.01 and $100,000.00.
             */
            amount: number;
            /** @description PIN must be exactly 6 digits. */
            pin: string;
            description?: null | string;
        };
        /**
         * @description Response returned after a successful withdrawal.
         *     Includes the created transaction and updated balance.
         */
        WithdrawResponse: {
            /** @description The created withdrawal transaction */
            transaction: components["schemas"]["TransactionResponse"];
            /**
             * Format: double
             * @description Updated account balance after the withdrawal
             */
            newBalance?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
