using AzureBank.Api.Mappers;
using AzureBank.Api.Services.Implementations;
using AzureBank.Api.Services.Interfaces;
using AzureBank.Infrastructure.Data;
using AzureBank.Shared.Constants;
using AzureBank.Shared.DTOs.Account;
using AzureBank.Shared.Entities;
using AzureBank.Shared.Enums;
using AzureBank.Shared.Exceptions;
using FluentAssertions;
using AzureBank.Tests.Fixtures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Logging;
using Moq;

namespace AzureBank.Tests.Unit.Services;

/// <summary>
/// Unit tests for AccountService.
/// Uses in-memory database for DbContext and mocks for other dependencies.
/// </summary>
public class AccountServiceTests : IDisposable
{
    private readonly AzureBankDbContext _context;
    private readonly Mock<IAccountAccessService> _accountAccessMock;
    private readonly AccountMapper _mapper;
    private readonly Mock<ILogger<AccountService>> _loggerMock;
    private readonly AccountService _sut; // System Under Test

    private readonly string _databaseName = Guid.NewGuid().ToString();
    private readonly InMemoryDatabaseRoot _databaseRoot = new();

    public AccountServiceTests()
    {
        /*
          `InMemoryTestModelCustomizer` is what lets these tests exist at all. Every CreateAccount
          test in this region used to carry
          `[Fact(Skip = "Requires SQL Server - RowVersion is auto-generated by DB")]`, which was
          never true: the customizer strips `byte[]` concurrency tokens, so InMemory has nothing to
          generate. Three of the four passed unchanged the moment the attribute came off.

          The database is NAMED and given an explicit root so a test can open a SECOND context over
          the same store — the only way to prove a write actually persisted rather than merely
          sitting in this context's change tracker.
        */
        var options = new DbContextOptionsBuilder<AzureBankDbContext>()
            .UseInMemoryDatabase(_databaseName, _databaseRoot)
            .ReplaceService<IModelCustomizer, InMemoryTestModelCustomizer>()
            .Options;

        _context = new AzureBankDbContext(options);
        _accountAccessMock = new Mock<IAccountAccessService>();
        _mapper = new AccountMapper();
        _loggerMock = new Mock<ILogger<AccountService>>();

        _sut = new AccountService(
            _context,
            _accountAccessMock.Object,
            _mapper,
            _loggerMock.Object);
    }

    public void Dispose()
    {
        _context.Dispose();
        GC.SuppressFinalize(this);
    }

    #region GetUserAccountsAsync Tests

    [Fact]
    public async Task GetUserAccountsAsync_WithExistingAccounts_ReturnsAccountList()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();

        // Act
        var result = await _sut.GetUserAccountsAsync(userId);

        // Assert
        result.Should().HaveCount(1);
        result.First().IsPrimary.Should().BeTrue();
    }

    [Fact]
    public async Task GetUserAccountsAsync_WithNoAccounts_ReturnsEmptyList()
    {
        // Arrange
        var userId = Guid.NewGuid();

        // Act
        var result = await _sut.GetUserAccountsAsync(userId);

        // Assert
        result.Should().BeEmpty();
    }

    [Fact]
    public async Task GetUserAccountsAsync_ExcludesDeletedAccounts()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var activeAccount = CreateTestAccount(userId, isPrimary: true);
        var deletedAccount = CreateTestAccount(userId, isPrimary: false);
        deletedAccount.IsDeleted = true;
        deletedAccount.DeletedAt = DateTime.UtcNow;

        _context.Accounts.AddRange(activeAccount, deletedAccount);
        await _context.SaveChangesAsync();

        // Act
        var result = await _sut.GetUserAccountsAsync(userId);

        // Assert
        result.Should().HaveCount(1);
        result.First().Id.Should().Be(activeAccount.Id);
    }

    [Fact]
    public async Task GetUserAccountsAsync_OrdersByPrimaryFirst()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var secondaryAccount = CreateTestAccount(userId, isPrimary: false);
        secondaryAccount.CreatedAt = DateTime.UtcNow.AddHours(-1); // Created first
        var primaryAccount = CreateTestAccount(userId, isPrimary: true);
        primaryAccount.CreatedAt = DateTime.UtcNow; // Created second

        _context.Accounts.AddRange(secondaryAccount, primaryAccount);
        await _context.SaveChangesAsync();

        // Act
        var result = await _sut.GetUserAccountsAsync(userId);

        // Assert
        result.Should().HaveCount(2);
        result.First().IsPrimary.Should().BeTrue();
    }

    [Fact]
    public async Task GetUserAccountsAsync_DoesNotReturnOtherUsersAccounts()
    {
        // Arrange
        var userId1 = Guid.NewGuid();
        var userId2 = Guid.NewGuid();
        var account1 = CreateTestAccount(userId1, isPrimary: true);
        var account2 = CreateTestAccount(userId2, isPrimary: true);

        _context.Accounts.AddRange(account1, account2);
        await _context.SaveChangesAsync();

        // Act
        var result = await _sut.GetUserAccountsAsync(userId1);

        // Assert
        result.Should().HaveCount(1);
        result.First().Id.Should().Be(account1.Id);
    }

    #endregion

    #region CreateAccountAsync Tests

    [Fact]
    public async Task CreateAccountAsync_WithValidRequest_CreatesAccount()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var request = new CreateAccountRequest
        {
            Name = "Test Savings Account",
            Type = AccountType.Savings
        };

        // Act
        var result = await _sut.CreateAccountAsync(userId, request);

        // Assert
        result.Name.Should().Be("Test Savings Account");
        result.Type.Should().Be(AccountType.Savings);
        result.Balance.Should().Be(0);
        result.IsPrimary.Should().BeFalse();
    }

    [Fact]
    public async Task CreateAccountAsync_ReturnsADistinctMaskedNumberEachTime()
    {
        /*
          This test was skipped as "Requires SQL Server - RowVersion", and neither half of that was
          the problem. Un-skipping it failed outright:

            Expected result.AccountNumber to match regex "^AB-\d{4}-\d{4}-\d{2}$",
            but "AB-****-****-81" does not match.

          It asserted the RAW number on a field the API masks by default (ADR-0020, applied in
          `AccountMapper.MaskAccountNumber`). The skip is why nobody noticed a test contradicting a
          shipped decision — a disabled test cannot report drift.

          The name was wrong too: it said "unique" while the body created ONE account and compared
          nothing. Both halves are asserted now, because the masked suffix is the only part a caller
          sees and two accounts sharing one is exactly the collision worth catching.
        */
        var userId = Guid.NewGuid();
        var first = await _sut.CreateAccountAsync(
            userId, new CreateAccountRequest { Name = "First", Type = AccountType.Checking });
        var second = await _sut.CreateAccountAsync(
            userId, new CreateAccountRequest { Name = "Second", Type = AccountType.Savings });

        first.AccountNumber.Should().MatchRegex(@"^AB-\*{4}-\*{4}-\d{2}$");
        second.AccountNumber.Should().MatchRegex(@"^AB-\*{4}-\*{4}-\d{2}$");

        // The RAW numbers must differ. Asserted on the entities, since the wire only ever shows the
        // last two digits and two different accounts can legitimately share those.
        var stored = await _context.Accounts.Where(a => a.UserId == userId).ToListAsync();
        stored.Should().HaveCount(2);
        stored.Select(a => a.AccountNumber).Distinct().Should().HaveCount(2);
        stored.Should().AllSatisfy(a => a.AccountNumber.Should().MatchRegex(@"^AB-\d{4}-\d{4}-\d{2}$"),
            "the DB keeps the real number; only the response is masked");
    }

    [Fact]
    public async Task CreateAccountAsync_PersistsAccountToDatabase()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var request = new CreateAccountRequest
        {
            Name = "Persisted Account",
            Type = AccountType.Checking
        };

        // Act
        var result = await _sut.CreateAccountAsync(userId, request);

        /*
          Re-read on a SECOND context over the same store, which is the whole point of the test.

          The original asserted through `_context.Accounts.FindAsync`, and `FindAsync` returns a
          tracked entity without going to the database — so it would have passed with the
          `SaveChangesAsync` inside `CreateAccountAsync` deleted. A persistence test that cannot
          fail when persistence is removed is not testing persistence.

          Proven by mutation, not by argument: commenting out that SaveChanges leaves the old
          assertion green and this one red.
        */
        await using var freshContext = new AzureBankDbContext(
            new DbContextOptionsBuilder<AzureBankDbContext>()
                .UseInMemoryDatabase(_databaseName, _databaseRoot)
                .ReplaceService<IModelCustomizer, InMemoryTestModelCustomizer>()
                .Options);

        var savedAccount = await freshContext.Accounts.SingleOrDefaultAsync(a => a.Id == result.Id);
        savedAccount.Should().NotBeNull();
        savedAccount!.Name.Should().Be("Persisted Account");
        savedAccount.UserId.Should().Be(userId, "the row must be owned by the caller, not just exist");
        savedAccount.Balance.Should().Be(0);
    }

    [Fact]
    public async Task CreateAccountAsync_NewAccountIsNotPrimary()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var request = new CreateAccountRequest
        {
            Name = "New Account",
            Type = AccountType.Savings
        };

        // Act
        var result = await _sut.CreateAccountAsync(userId, request);

        // Assert
        result.IsPrimary.Should().BeFalse();
    }

    #endregion

    #region UpdateAccountAsync Tests

    [Fact]
    public async Task UpdateAccountAsync_WithValidRequest_UpdatesAccountName()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        account.Id = accountId;
        account.Name = "Original Name";

        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        var request = new UpdateAccountRequest { Name = "Updated Name" };

        // Act
        var result = await _sut.UpdateAccountAsync(accountId, userId, request);

        // Assert
        result.Name.Should().Be("Updated Name");
    }

    [Fact]
    public async Task UpdateAccountAsync_SetsUpdatedAtTimestamp()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        account.Id = accountId;
        var originalUpdatedAt = account.UpdatedAt;

        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        var request = new UpdateAccountRequest { Name = "New Name" };

        // Act
        await _sut.UpdateAccountAsync(accountId, userId, request);

        // Assert
        account.UpdatedAt.Should().BeOnOrAfter(originalUpdatedAt);
    }

    #endregion

    #region DeleteAccountAsync Tests

    [Fact]
    public async Task DeleteAccountAsync_WithNonZeroBalance_ThrowsBusinessRuleException()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: false);
        account.Id = accountId;
        account.Balance = 100m;

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        // Act
        var act = () => _sut.DeleteAccountAsync(accountId, userId);

        // Assert
        await act.Should()
            .ThrowAsync<BusinessRuleException>()
            .WithMessage("*non-zero balance*");
    }

    [Fact]
    public async Task DeleteAccountAsync_WithPrimaryAccount_ThrowsBusinessRuleException()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        account.Id = accountId;
        account.Balance = 0;

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        // Act
        var act = () => _sut.DeleteAccountAsync(accountId, userId);

        // Assert
        await act.Should()
            .ThrowAsync<BusinessRuleException>()
            .WithMessage("*primary account*");
    }

    [Fact]
    public async Task DeleteAccountAsync_WithValidAccount_SoftDeletes()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: false);
        account.Id = accountId;
        account.Balance = 0;

        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        // Act
        await _sut.DeleteAccountAsync(accountId, userId);

        // Assert
        var deletedAccount = await _context.Accounts.FindAsync(accountId);
        deletedAccount!.IsDeleted.Should().BeTrue();
        deletedAccount.DeletedAt.Should().NotBeNull();
    }

    [Fact]
    public async Task DeleteAccountAsync_WithNegativeBalance_ThrowsBusinessRuleException()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: false);
        account.Id = accountId;
        account.Balance = -50m; // Negative balance

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        // Act
        var act = () => _sut.DeleteAccountAsync(accountId, userId);

        // Assert
        await act.Should()
            .ThrowAsync<BusinessRuleException>()
            .WithMessage("*non-zero balance*");
    }

    [Fact]
    public async Task DeleteAccountAsync_AuditsTheClosure_AsASecurityEvent()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: false);
        account.Id = accountId;
        account.Balance = 0;

        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        // Act
        await _sut.DeleteAccountAsync(accountId, userId);

        /*
          Assert — this was a plain LogInformation("Soft deleted account {AccountId}") until now, so
          it never reached the stream an operator alerts on while AccountNumberRevealed, a strictly
          smaller act, did. The ACTING USER is asserted as well as the account, because a deleted
          account is invisible to every read path afterwards (global query filter; measured, the
          owner's own GET by id answers 404 ACCOUNT_NOT_FOUND) — this line is the only surviving
          record of whose it was.
        */
        _loggerMock.Verify(l => l.Log(
            LogLevel.Information,
            It.IsAny<EventId>(),
            It.Is<It.IsAnyType>((state, _) =>
                state.ToString()!.Contains(SecurityEvents.AccountDeleted) &&
                state.ToString()!.Contains(userId.ToString()) &&
                state.ToString()!.Contains(accountId.ToString())),
            It.IsAny<Exception?>(),
            It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
    }

    [Theory]
    [InlineData(true, 0)]      // primary account   -> PRIMARY_ACCOUNT_DELETE
    [InlineData(false, 50)]    // non-zero balance  -> NON_ZERO_BALANCE
    public async Task DeleteAccountAsync_WhenRefused_AuditsNoClosure(bool isPrimary, decimal balance)
    {
        /*
          The negative control, and the reason the pair is worth more than the positive alone: an
          event named "AccountDeleted" that also fired on a REFUSED attempt would make the audit
          stream lie in the direction that matters — an operator reading it would see closures that
          never happened. Same posture as GetFullAccountNumberAsync's denied-attempt test above.
        */
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: isPrimary);
        account.Id = accountId;
        account.Balance = balance;

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        await _sut.Invoking(sut => sut.DeleteAccountAsync(accountId, userId))
            .Should().ThrowAsync<BusinessRuleException>();

        _loggerMock.Verify(l => l.Log(
            It.IsAny<LogLevel>(),
            It.IsAny<EventId>(),
            It.Is<It.IsAnyType>((state, _) =>
                state.ToString()!.Contains(SecurityEvents.AccountDeleted)),
            It.IsAny<Exception?>(),
            It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Never);
    }

    #endregion

    #region GetBalanceAsync Tests

    [Fact]
    public async Task GetBalanceAsync_WithNullAtTime_ReturnsCurrentBalance()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        account.Id = accountId;
        account.Balance = 500m;

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        // Act
        var result = await _sut.GetBalanceAsync(accountId, userId, atTime: null);

        // Assert
        result.Balance.Should().Be(500m);
        result.IsHistorical.Should().BeFalse();
    }

    [Fact]
    public async Task GetBalanceAsync_WithFutureDate_ReturnsCurrentBalance()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        account.Id = accountId;
        account.Balance = 1000m;

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        var futureDate = DateTime.UtcNow.AddDays(1);

        // Act
        var result = await _sut.GetBalanceAsync(accountId, userId, atTime: futureDate);

        // Assert
        result.Balance.Should().Be(1000m);
        result.IsHistorical.Should().BeFalse();
    }


[Fact]
    public async Task GetBalanceAsync_WithNoTransactions_ReturnsZeroHistoricalBalance()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        account.Id = accountId;
        account.Balance = 1000m;

        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();

        _accountAccessMock
            .Setup(x => x.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ReturnsAsync(account);

        var historicalDate = DateTime.UtcNow.AddDays(-30);

        // Act
        var result = await _sut.GetBalanceAsync(accountId, userId, atTime: historicalDate);

        // Assert
        result.Balance.Should().Be(0);
        result.IsHistorical.Should().BeTrue();
    }

    #endregion

    #region GetFullAccountNumberAsync Tests

    [Fact]
    public async Task GetFullAccountNumberAsync_ForOwnedAccount_ReturnsVerbatimUnmaskedNumber()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: true);
        _accountAccessMock
            .Setup(a => a.GetAccountWithOwnershipCheckAsync(account.Id, userId))
            .ReturnsAsync(account);

        // Act
        var result = await _sut.GetFullAccountNumberAsync(account.Id, userId);

        // Assert — the ONE read that returns the entity value verbatim, not the mask.
        result.AccountId.Should().Be(account.Id);
        result.AccountNumber.Should().Be(account.AccountNumber);
        result.AccountNumber.Should().NotContain("*");
    }

    [Fact]
    public async Task GetFullAccountNumberAsync_AuditsTheReveal_WithoutLoggingTheNumber()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var account = CreateTestAccount(userId, isPrimary: false);
        _accountAccessMock
            .Setup(a => a.GetAccountWithOwnershipCheckAsync(account.Id, userId))
            .ReturnsAsync(account);

        // Act
        await _sut.GetFullAccountNumberAsync(account.Id, userId);

        // Assert — the SecurityEvent fires with Guids only. PII redaction is opt-in per
        // call site, so the rendered message must never contain the account number.
        _loggerMock.Verify(l => l.Log(
            LogLevel.Information,
            It.IsAny<EventId>(),
            It.Is<It.IsAnyType>((state, _) =>
                state.ToString()!.Contains("AccountNumberRevealed") &&
                state.ToString()!.Contains(userId.ToString()) &&
                state.ToString()!.Contains(account.Id.ToString()) &&
                !state.ToString()!.Contains(account.AccountNumber)),
            It.IsAny<Exception?>(),
            It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
    }

    [Fact]
    public async Task GetFullAccountNumberAsync_ForForeignAccount_PropagatesAuthorizationFailure()
    {
        // Arrange — ownership goes through the SAME central check as every other read.
        var accountId = Guid.NewGuid();
        var userId = Guid.NewGuid();
        _accountAccessMock
            .Setup(a => a.GetAccountWithOwnershipCheckAsync(accountId, userId))
            .ThrowsAsync(new AuthorizationException("You do not have access to this account."));

        // Act & Assert
        await _sut.Invoking(s => s.GetFullAccountNumberAsync(accountId, userId))
            .Should().ThrowAsync<AuthorizationException>();

        // No audit line for a denied attempt with this event name — the denial is logged
        // by the exception pipeline; AccountNumberRevealed must mean "value was returned".
        _loggerMock.Verify(l => l.Log(
            It.IsAny<LogLevel>(),
            It.IsAny<EventId>(),
            It.Is<It.IsAnyType>((state, _) => state.ToString()!.Contains("AccountNumberRevealed")),
            It.IsAny<Exception?>(),
            It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Never);
    }

    #endregion

    #region Helper Methods

    private static Account CreateTestAccount(Guid userId, bool isPrimary)
    {
        return new Account
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            AccountNumber = $"AB-{Random.Shared.Next(1000, 9999)}-{Random.Shared.Next(1000, 9999)}-{Random.Shared.Next(10, 99)}",
            Name = "Test Account",
            Type = AccountType.Checking,
            Balance = 0,
            IsPrimary = isPrimary,
            CreatedAt = DateTime.UtcNow,
            RowVersion = [0, 0, 0, 0, 0, 0, 0, 1], // Mock row version for in-memory DB
            User = null! // Navigation property not needed for unit tests
        };
    }

    #endregion

    // Historical balance now lives in Integration/HistoricalBalanceSqlServerTests.cs: it needs a
    // row genuinely older than the run, which only an out-of-band UPDATE can produce.
}
