namespace AzureBank.Shared.Entities;

/// <summary>
/// One row per notice the account holder is OWED and has not yet been told: the durable half of the
/// notification NIST SP 800-63B-4 §4.1.2.1 requires when an authenticator is added (ADR-0045).
/// </summary>
/// <remarks>
/// <para>
/// A ROW IS NOT A NOTICE. What this table records is the FACT that a notice is owed, written in the
/// same save as the action that owes it — the PIN enrolment and its <see cref="AuditEvent"/> — so
/// the obligation cannot be lost when the enrolment commits and cannot survive when it rolls back
/// (ADR-0044 D1, applied to a second row). The notice itself is rendered later — by the API's own
/// relay on a period (ADR-0048), or by the operator tool's <c>notify</c> verb — on a different
/// connection and outside the request: the session that enrolled the PIN cannot read this table,
/// cannot change the address the notice will be addressed to, and cannot suppress the sweep or the
/// run. That independence is the clause the design meets; delivery is
/// the clause it does not, and ADR-0045 says where it stops.
/// </para>
/// <para>
/// AN OUTBOX WITH A PUMP, since 2026-09-04. Until then this paragraph said the opposite — nothing
/// in the API read it, nothing drained it on a timer, the anchor's decision for the anchor's reason
/// — and ADR-0048 reversed it: <c>NoticeRelayService</c> claims the free owed rows under the lease
/// below and delivers them, when <c>Notices:Runner</c> names the API. The verb remains for a store
/// where nothing runs.
/// </para>
/// <para>
/// NO ADDRESS COLUMN, on purpose. The recipient is joined from the account at rendering time, which
/// keeps personal data out of a table that grows for the life of the account and lets erasure
/// happen by cascade with the user. A snapshot taken at enrolment would not defend against an
/// attacker who changed the address BEFORE enrolling — only notifying the OLD address of the change
/// does that — and no change-email endpoint exists today; the day one does, this sentence is the
/// trigger to revisit.
/// </para>
/// <para>
/// Not a <c>BaseEntity</c>, like <see cref="StepUpAuthorization"/>: explicit instants, no managed
/// timestamps, no soft delete. Nothing deletes from this table; a delivered row is the only record
/// that a notice was rendered at all.
/// </para>
/// </remarks>
public class SubscriberNotice
{
    /// <summary>
    /// Assigned by the writer (UUIDv7, like <see cref="AuditEvent.Id"/>) rather than generated by
    /// the store, so the InMemory provider and SQL Server agree on it. It is also the reference the
    /// rendered notice carries, and the only thing a recipient needs to quote back.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>The account holder the notice is owed to. The address is theirs, read at delivery.</summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Which event owes the notice — a <c>SecurityEvents</c> constant, the same vocabulary as the
    /// audit row written beside it. Two values are written today: <c>PinEnrolled</c> when a PIN is
    /// bound for the first time (ADR-0045) and <c>PinChanged</c> when an existing one is replaced
    /// (ADR-0047). Until 2026-09-04 this sentence said there was exactly one.
    /// </summary>
    public required string Event { get; set; }

    /// <summary>When the event happened (UTC), read from the request that recorded it.</summary>
    public DateTime OccurredAt { get; set; }

    /// <summary>
    /// When a runner — the API's relay or the operator tool — rendered the notice (UTC). Null while
    /// the notice is still owed.
    /// A concurrency token, so two runs cannot both claim to have rendered one notice: the second
    /// UPDATE carries <c>WHERE DeliveredAt IS NULL</c> and loses loudly.
    /// </summary>
    public DateTime? DeliveredAt { get; set; }

    /// <summary>
    /// What the rendering produced — for the pickup-directory transport, the file name. Present
    /// exactly when <see cref="DeliveredAt"/> is; the database refuses one without the other.
    /// </summary>
    public string? DeliveryReceipt { get; set; }

    /// <summary>
    /// Until when a runner holds this row (UTC), or null when nobody does (ADR-0048). A claim is a
    /// set-based UPDATE that takes every owed row whose lease is null or expired, so two runners
    /// cannot hold one row at the same moment. It cannot stop a runner that delivers, dies before
    /// marking, and is succeeded after the lease lapses. With a sending transport that row would go
    /// out twice; with the pickup directory the second attempt is refused by the exclusive create
    /// and the row stays owed beside the file it produced, for the runbook to clear. The ADR calls
    /// the protocol at-least-once rather than letting this column imply otherwise.
    /// </summary>
    public DateTime? LeasedUntil { get; set; }

    /// <summary>
    /// Which runner holds the lease — a name for the log, never a secret. Present exactly when
    /// <see cref="LeasedUntil"/> is; the database refuses one without the other.
    /// </summary>
    public string? LeasedBy { get; set; }
}
